{
  // Specify the parent parser.
  overrides="app.cash.sqldelight.dialects.postgresql.grammar.PostgreSqlParser"
  elementTypeClass = "com.alecstrong.sql.psi.core.SqlElementType"

  implements="com.alecstrong.sql.psi.core.psi.SqlCompositeElement"
  extends="com.alecstrong.sql.psi.core.psi.SqlCompositeElementImpl"
  psiClassPrefix = "PgSearch"

  parserImports=[
    "static com.alecstrong.sql.psi.core.psi.SqlTypes.COMMA"
    "static com.alecstrong.sql.psi.core.psi.SqlTypes.LP"
    "static com.alecstrong.sql.psi.core.psi.SqlTypes.RP"

    "static com.alecstrong.sql.psi.core.SqlParserUtil.signedNumberExt"
    "static com.alecstrong.sql.psi.core.SqlParser.signed_number_real"

    "static com.alecstrong.sql.psi.core.SqlParserUtil.columnExprExt"
    "static com.alecstrong.sql.psi.core.SqlParser.column_expr_real"

    "static com.alecstrong.sql.psi.core.SqlParser.expr"
  ]
}

type_name ::= simple_data_type | ngram_data_type | source_code_data_type | icu_data_type | regex_pattern_data_type | whitespace_data_type
 | literal_data_type | literal_normalized_data_type | unicode_words_data_type | chinese_compatible_data_type {
  extends = "app.cash.sqldelight.dialects.postgresql.grammar.psi.impl.PostgreSqlTypeNameImpl"
  implements = "app.cash.sqldelight.dialects.postgresql.grammar.psi.PostgreSqlTypeName"
}

simple_data_type ::= 'SIMPLE' [ LP {string_literal} [ ( COMMA {string_literal} ) * ] RP ]

ngram_data_type ::= 'NGRAM' LP sql_signed_number COMMA sql_signed_number [ COMMA {string_literal} ] RP

source_code_data_type ::= 'SOURCE_CODE'

icu_data_type ::= 'ICU'

regex_pattern_data_type ::= 'REGEX_PATTERN' LP {string_literal} RP

whitespace_data_type ::= 'WHITESPACE'

literal_normalized_data_type ::= 'LITERAL_NORMALIZED' [ LP {string_literal} [ ( COMMA {string_literal} ) * ] RP ]

literal_data_type ::= 'LITERAL'

unicode_words_data_type ::= 'UNICODE_WORDS' [ LP {string_literal} RP ]

chinese_compatible_data_type ::= 'CHINESE_COMPATIBLE'

index_method ::= 'bm25' {
  extends = "app.cash.sqldelight.dialects.postgresql.grammar.psi.impl.PostgreSqlIndexMethodImpl"
  implements = "app.cash.sqldelight.dialects.postgresql.grammar.psi.PostgreSqlIndexMethod"
}

storage_parameters ::= 'key_field' | 'numeric_fields' | 'text_fields' | 'json_fields' {
  extends = "app.cash.sqldelight.dialects.postgresql.grammar.psi.impl.PostgreSqlStorageParameterImpl"
  implements = "app.cash.sqldelight.dialects.postgresql.grammar.psi.PostgreSqlStorageParameter"
}

private sql_signed_number ::= <<signedNumberExt <<signed_number_real>>>>

private sql_column_expr ::= <<columnExprExt <<column_expr_real>>>>

proximity_operator ::= '@@@'

proximity_operator_expression ::= sql_column_expr proximity_operator <<expr '-1'>> {
  mixin = "griffio.grammar.mixins.PgSearchProximityOperatorMixin"
  pin = 2
}

match_bi_junction_operator ::= '|||' | '&&&'

match_bi_junction_operator_expression ::= sql_column_expr match_bi_junction_operator <<expr '-1'>> {
  mixin = "griffio.grammar.mixins.PgSearchMatchOperatorMixin"
  pin = 2
}

phrase_operator ::= '###'

phrase_operator_expression ::= sql_column_expr phrase_operator <<expr '-1'>> {
  mixin = "griffio.grammar.mixins.PgSearchPhraseOperatorMixin"
  pin = 2
}

term_operator ::= '==='

term_operator_expression ::= sql_column_expr term_operator <<expr '-1'>> {
  mixin = "griffio.grammar.mixins.PgSearchTermOperatorMixin"
  pin = 2
}

extension_expr ::= term_operator_expression | proximity_operator_expression | match_bi_junction_operator_expression | phrase_operator_expression {
  extends = "app.cash.sqldelight.dialects.postgresql.grammar.psi.impl.PostgreSqlExtensionExprImpl"
  implements = "app.cash.sqldelight.dialects.postgresql.grammar.psi.PostgreSqlExtensionExpr"
}
